if(NOT EXISTS "/home/nobelc/Projects/kls/install_manifest.txt")
  message(FATAL_ERROR "Cannot find install manifest: /home/nobelc/Projects/kls/install_manifest.txt")
endif()

file(READ "/home/nobelc/Projects/kls/install_manifest.txt" files)
string(REGEX REPLACE "\n" ";" files "${files}")
foreach(file ${files})
  message(STATUS "Uninstalling $ENV{DESTDIR}${file}")
  if(IS_SYMLINK "$ENV{DESTDIR}${file}" OR EXISTS "$ENV{DESTDIR}${file}")
    file(REMOVE "$ENV{DESTDIR}${file}")
  else()
    message(STATUS "File $ENV{DESTDIR}${file} does not exist.")
  endif()
endforeach()
