# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nobelc/Projects/kls

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nobelc/Projects/kls

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"man\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nobelc/Projects/kls/CMakeFiles /home/nobelc/Projects/kls//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nobelc/Projects/kls/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kls_core

# Build rule for target.
kls_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kls_core
.PHONY : kls_core

# fast build rule for target.
kls_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/build
.PHONY : kls_core/fast

#=============================================================================
# Target rules for targets named kls_scanner

# Build rule for target.
kls_scanner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kls_scanner
.PHONY : kls_scanner

# fast build rule for target.
kls_scanner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_scanner.dir/build.make CMakeFiles/kls_scanner.dir/build
.PHONY : kls_scanner/fast

#=============================================================================
# Target rules for targets named kls

# Build rule for target.
kls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kls
.PHONY : kls

# fast build rule for target.
kls/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls.dir/build.make CMakeFiles/kls.dir/build
.PHONY : kls/fast

#=============================================================================
# Target rules for targets named compress_man

# Build rule for target.
compress_man: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compress_man
.PHONY : compress_man

# fast build rule for target.
compress_man/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compress_man.dir/build.make CMakeFiles/compress_man.dir/build
.PHONY : compress_man/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named kls_tests

# Build rule for target.
kls_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kls_tests
.PHONY : kls_tests

# fast build rule for target.
kls_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/kls_tests.dir/build.make tests/CMakeFiles/kls_tests.dir/build
.PHONY : kls_tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/CAPABILITIES-register/capabilities-register-log.o: src/CAPABILITIES-register/capabilities-register-log.cpp.o
.PHONY : src/CAPABILITIES-register/capabilities-register-log.o

# target to build an object file
src/CAPABILITIES-register/capabilities-register-log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/CAPABILITIES-register/capabilities-register-log.cpp.o
.PHONY : src/CAPABILITIES-register/capabilities-register-log.cpp.o

src/CAPABILITIES-register/capabilities-register-log.i: src/CAPABILITIES-register/capabilities-register-log.cpp.i
.PHONY : src/CAPABILITIES-register/capabilities-register-log.i

# target to preprocess a source file
src/CAPABILITIES-register/capabilities-register-log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/CAPABILITIES-register/capabilities-register-log.cpp.i
.PHONY : src/CAPABILITIES-register/capabilities-register-log.cpp.i

src/CAPABILITIES-register/capabilities-register-log.s: src/CAPABILITIES-register/capabilities-register-log.cpp.s
.PHONY : src/CAPABILITIES-register/capabilities-register-log.s

# target to generate assembly for a file
src/CAPABILITIES-register/capabilities-register-log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/CAPABILITIES-register/capabilities-register-log.cpp.s
.PHONY : src/CAPABILITIES-register/capabilities-register-log.cpp.s

src/CAPABILITIES-register/capabilities-register.o: src/CAPABILITIES-register/capabilities-register.cpp.o
.PHONY : src/CAPABILITIES-register/capabilities-register.o

# target to build an object file
src/CAPABILITIES-register/capabilities-register.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/CAPABILITIES-register/capabilities-register.cpp.o
.PHONY : src/CAPABILITIES-register/capabilities-register.cpp.o

src/CAPABILITIES-register/capabilities-register.i: src/CAPABILITIES-register/capabilities-register.cpp.i
.PHONY : src/CAPABILITIES-register/capabilities-register.i

# target to preprocess a source file
src/CAPABILITIES-register/capabilities-register.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/CAPABILITIES-register/capabilities-register.cpp.i
.PHONY : src/CAPABILITIES-register/capabilities-register.cpp.i

src/CAPABILITIES-register/capabilities-register.s: src/CAPABILITIES-register/capabilities-register.cpp.s
.PHONY : src/CAPABILITIES-register/capabilities-register.s

# target to generate assembly for a file
src/CAPABILITIES-register/capabilities-register.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/CAPABILITIES-register/capabilities-register.cpp.s
.PHONY : src/CAPABILITIES-register/capabilities-register.cpp.s

src/CAPABILITIES-register/print-capabilities.o: src/CAPABILITIES-register/print-capabilities.cpp.o
.PHONY : src/CAPABILITIES-register/print-capabilities.o

# target to build an object file
src/CAPABILITIES-register/print-capabilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/CAPABILITIES-register/print-capabilities.cpp.o
.PHONY : src/CAPABILITIES-register/print-capabilities.cpp.o

src/CAPABILITIES-register/print-capabilities.i: src/CAPABILITIES-register/print-capabilities.cpp.i
.PHONY : src/CAPABILITIES-register/print-capabilities.i

# target to preprocess a source file
src/CAPABILITIES-register/print-capabilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/CAPABILITIES-register/print-capabilities.cpp.i
.PHONY : src/CAPABILITIES-register/print-capabilities.cpp.i

src/CAPABILITIES-register/print-capabilities.s: src/CAPABILITIES-register/print-capabilities.cpp.s
.PHONY : src/CAPABILITIES-register/print-capabilities.s

# target to generate assembly for a file
src/CAPABILITIES-register/print-capabilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/CAPABILITIES-register/print-capabilities.cpp.s
.PHONY : src/CAPABILITIES-register/print-capabilities.cpp.s

src/SUID-SGID-register/health-register.o: src/SUID-SGID-register/health-register.cpp.o
.PHONY : src/SUID-SGID-register/health-register.o

# target to build an object file
src/SUID-SGID-register/health-register.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/SUID-SGID-register/health-register.cpp.o
.PHONY : src/SUID-SGID-register/health-register.cpp.o

src/SUID-SGID-register/health-register.i: src/SUID-SGID-register/health-register.cpp.i
.PHONY : src/SUID-SGID-register/health-register.i

# target to preprocess a source file
src/SUID-SGID-register/health-register.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/SUID-SGID-register/health-register.cpp.i
.PHONY : src/SUID-SGID-register/health-register.cpp.i

src/SUID-SGID-register/health-register.s: src/SUID-SGID-register/health-register.cpp.s
.PHONY : src/SUID-SGID-register/health-register.s

# target to generate assembly for a file
src/SUID-SGID-register/health-register.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/SUID-SGID-register/health-register.cpp.s
.PHONY : src/SUID-SGID-register/health-register.cpp.s

src/SUID-SGID-register/print-health-flags.o: src/SUID-SGID-register/print-health-flags.cpp.o
.PHONY : src/SUID-SGID-register/print-health-flags.o

# target to build an object file
src/SUID-SGID-register/print-health-flags.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/SUID-SGID-register/print-health-flags.cpp.o
.PHONY : src/SUID-SGID-register/print-health-flags.cpp.o

src/SUID-SGID-register/print-health-flags.i: src/SUID-SGID-register/print-health-flags.cpp.i
.PHONY : src/SUID-SGID-register/print-health-flags.i

# target to preprocess a source file
src/SUID-SGID-register/print-health-flags.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/SUID-SGID-register/print-health-flags.cpp.i
.PHONY : src/SUID-SGID-register/print-health-flags.cpp.i

src/SUID-SGID-register/print-health-flags.s: src/SUID-SGID-register/print-health-flags.cpp.s
.PHONY : src/SUID-SGID-register/print-health-flags.s

# target to generate assembly for a file
src/SUID-SGID-register/print-health-flags.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/SUID-SGID-register/print-health-flags.cpp.s
.PHONY : src/SUID-SGID-register/print-health-flags.cpp.s

src/SUID-SGID-register/suid-sgid-register-table.o: src/SUID-SGID-register/suid-sgid-register-table.cpp.o
.PHONY : src/SUID-SGID-register/suid-sgid-register-table.o

# target to build an object file
src/SUID-SGID-register/suid-sgid-register-table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/SUID-SGID-register/suid-sgid-register-table.cpp.o
.PHONY : src/SUID-SGID-register/suid-sgid-register-table.cpp.o

src/SUID-SGID-register/suid-sgid-register-table.i: src/SUID-SGID-register/suid-sgid-register-table.cpp.i
.PHONY : src/SUID-SGID-register/suid-sgid-register-table.i

# target to preprocess a source file
src/SUID-SGID-register/suid-sgid-register-table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/SUID-SGID-register/suid-sgid-register-table.cpp.i
.PHONY : src/SUID-SGID-register/suid-sgid-register-table.cpp.i

src/SUID-SGID-register/suid-sgid-register-table.s: src/SUID-SGID-register/suid-sgid-register-table.cpp.s
.PHONY : src/SUID-SGID-register/suid-sgid-register-table.s

# target to generate assembly for a file
src/SUID-SGID-register/suid-sgid-register-table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/SUID-SGID-register/suid-sgid-register-table.cpp.s
.PHONY : src/SUID-SGID-register/suid-sgid-register-table.cpp.s

src/analyzers/capability_analyzer.o: src/analyzers/capability_analyzer.cpp.o
.PHONY : src/analyzers/capability_analyzer.o

# target to build an object file
src/analyzers/capability_analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/analyzers/capability_analyzer.cpp.o
.PHONY : src/analyzers/capability_analyzer.cpp.o

src/analyzers/capability_analyzer.i: src/analyzers/capability_analyzer.cpp.i
.PHONY : src/analyzers/capability_analyzer.i

# target to preprocess a source file
src/analyzers/capability_analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/analyzers/capability_analyzer.cpp.i
.PHONY : src/analyzers/capability_analyzer.cpp.i

src/analyzers/capability_analyzer.s: src/analyzers/capability_analyzer.cpp.s
.PHONY : src/analyzers/capability_analyzer.s

# target to generate assembly for a file
src/analyzers/capability_analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/analyzers/capability_analyzer.cpp.s
.PHONY : src/analyzers/capability_analyzer.cpp.s

src/analyzers/health_analyzer.o: src/analyzers/health_analyzer.cpp.o
.PHONY : src/analyzers/health_analyzer.o

# target to build an object file
src/analyzers/health_analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/analyzers/health_analyzer.cpp.o
.PHONY : src/analyzers/health_analyzer.cpp.o

src/analyzers/health_analyzer.i: src/analyzers/health_analyzer.cpp.i
.PHONY : src/analyzers/health_analyzer.i

# target to preprocess a source file
src/analyzers/health_analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/analyzers/health_analyzer.cpp.i
.PHONY : src/analyzers/health_analyzer.cpp.i

src/analyzers/health_analyzer.s: src/analyzers/health_analyzer.cpp.s
.PHONY : src/analyzers/health_analyzer.s

# target to generate assembly for a file
src/analyzers/health_analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/analyzers/health_analyzer.cpp.s
.PHONY : src/analyzers/health_analyzer.cpp.s

src/cli/command/list.o: src/cli/command/list.cpp.o
.PHONY : src/cli/command/list.o

# target to build an object file
src/cli/command/list.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/command/list.cpp.o
.PHONY : src/cli/command/list.cpp.o

src/cli/command/list.i: src/cli/command/list.cpp.i
.PHONY : src/cli/command/list.i

# target to preprocess a source file
src/cli/command/list.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/command/list.cpp.i
.PHONY : src/cli/command/list.cpp.i

src/cli/command/list.s: src/cli/command/list.cpp.s
.PHONY : src/cli/command/list.s

# target to generate assembly for a file
src/cli/command/list.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/command/list.cpp.s
.PHONY : src/cli/command/list.cpp.s

src/cli/error/error_handler.o: src/cli/error/error_handler.cpp.o
.PHONY : src/cli/error/error_handler.o

# target to build an object file
src/cli/error/error_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/error/error_handler.cpp.o
.PHONY : src/cli/error/error_handler.cpp.o

src/cli/error/error_handler.i: src/cli/error/error_handler.cpp.i
.PHONY : src/cli/error/error_handler.i

# target to preprocess a source file
src/cli/error/error_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/error/error_handler.cpp.i
.PHONY : src/cli/error/error_handler.cpp.i

src/cli/error/error_handler.s: src/cli/error/error_handler.cpp.s
.PHONY : src/cli/error/error_handler.s

# target to generate assembly for a file
src/cli/error/error_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/error/error_handler.cpp.s
.PHONY : src/cli/error/error_handler.cpp.s

src/cli/option/option-get-option.o: src/cli/option/option-get-option.cpp.o
.PHONY : src/cli/option/option-get-option.o

# target to build an object file
src/cli/option/option-get-option.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/option-get-option.cpp.o
.PHONY : src/cli/option/option-get-option.cpp.o

src/cli/option/option-get-option.i: src/cli/option/option-get-option.cpp.i
.PHONY : src/cli/option/option-get-option.i

# target to preprocess a source file
src/cli/option/option-get-option.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/option-get-option.cpp.i
.PHONY : src/cli/option/option-get-option.cpp.i

src/cli/option/option-get-option.s: src/cli/option/option-get-option.cpp.s
.PHONY : src/cli/option/option-get-option.s

# target to generate assembly for a file
src/cli/option/option-get-option.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/option-get-option.cpp.s
.PHONY : src/cli/option/option-get-option.cpp.s

src/cli/option/option-information.o: src/cli/option/option-information.cpp.o
.PHONY : src/cli/option/option-information.o

# target to build an object file
src/cli/option/option-information.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/option-information.cpp.o
.PHONY : src/cli/option/option-information.cpp.o

src/cli/option/option-information.i: src/cli/option/option-information.cpp.i
.PHONY : src/cli/option/option-information.i

# target to preprocess a source file
src/cli/option/option-information.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/option-information.cpp.i
.PHONY : src/cli/option/option-information.cpp.i

src/cli/option/option-information.s: src/cli/option/option-information.cpp.s
.PHONY : src/cli/option/option-information.s

# target to generate assembly for a file
src/cli/option/option-information.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/option-information.cpp.s
.PHONY : src/cli/option/option-information.cpp.s

src/cli/option/special-option/help-handler.o: src/cli/option/special-option/help-handler.cpp.o
.PHONY : src/cli/option/special-option/help-handler.o

# target to build an object file
src/cli/option/special-option/help-handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/special-option/help-handler.cpp.o
.PHONY : src/cli/option/special-option/help-handler.cpp.o

src/cli/option/special-option/help-handler.i: src/cli/option/special-option/help-handler.cpp.i
.PHONY : src/cli/option/special-option/help-handler.i

# target to preprocess a source file
src/cli/option/special-option/help-handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/special-option/help-handler.cpp.i
.PHONY : src/cli/option/special-option/help-handler.cpp.i

src/cli/option/special-option/help-handler.s: src/cli/option/special-option/help-handler.cpp.s
.PHONY : src/cli/option/special-option/help-handler.s

# target to generate assembly for a file
src/cli/option/special-option/help-handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/special-option/help-handler.cpp.s
.PHONY : src/cli/option/special-option/help-handler.cpp.s

src/cli/option/special-option/version-handler.o: src/cli/option/special-option/version-handler.cpp.o
.PHONY : src/cli/option/special-option/version-handler.o

# target to build an object file
src/cli/option/special-option/version-handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/special-option/version-handler.cpp.o
.PHONY : src/cli/option/special-option/version-handler.cpp.o

src/cli/option/special-option/version-handler.i: src/cli/option/special-option/version-handler.cpp.i
.PHONY : src/cli/option/special-option/version-handler.i

# target to preprocess a source file
src/cli/option/special-option/version-handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/special-option/version-handler.cpp.i
.PHONY : src/cli/option/special-option/version-handler.cpp.i

src/cli/option/special-option/version-handler.s: src/cli/option/special-option/version-handler.cpp.s
.PHONY : src/cli/option/special-option/version-handler.s

# target to generate assembly for a file
src/cli/option/special-option/version-handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/option/special-option/version-handler.cpp.s
.PHONY : src/cli/option/special-option/version-handler.cpp.s

src/cli/parser/executor.o: src/cli/parser/executor.cpp.o
.PHONY : src/cli/parser/executor.o

# target to build an object file
src/cli/parser/executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/executor.cpp.o
.PHONY : src/cli/parser/executor.cpp.o

src/cli/parser/executor.i: src/cli/parser/executor.cpp.i
.PHONY : src/cli/parser/executor.i

# target to preprocess a source file
src/cli/parser/executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/executor.cpp.i
.PHONY : src/cli/parser/executor.cpp.i

src/cli/parser/executor.s: src/cli/parser/executor.cpp.s
.PHONY : src/cli/parser/executor.s

# target to generate assembly for a file
src/cli/parser/executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/executor.cpp.s
.PHONY : src/cli/parser/executor.cpp.s

src/cli/parser/parsing.o: src/cli/parser/parsing.cpp.o
.PHONY : src/cli/parser/parsing.o

# target to build an object file
src/cli/parser/parsing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/parsing.cpp.o
.PHONY : src/cli/parser/parsing.cpp.o

src/cli/parser/parsing.i: src/cli/parser/parsing.cpp.i
.PHONY : src/cli/parser/parsing.i

# target to preprocess a source file
src/cli/parser/parsing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/parsing.cpp.i
.PHONY : src/cli/parser/parsing.cpp.i

src/cli/parser/parsing.s: src/cli/parser/parsing.cpp.s
.PHONY : src/cli/parser/parsing.s

# target to generate assembly for a file
src/cli/parser/parsing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/parsing.cpp.s
.PHONY : src/cli/parser/parsing.cpp.s

src/cli/parser/tokenization.o: src/cli/parser/tokenization.cpp.o
.PHONY : src/cli/parser/tokenization.o

# target to build an object file
src/cli/parser/tokenization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/tokenization.cpp.o
.PHONY : src/cli/parser/tokenization.cpp.o

src/cli/parser/tokenization.i: src/cli/parser/tokenization.cpp.i
.PHONY : src/cli/parser/tokenization.i

# target to preprocess a source file
src/cli/parser/tokenization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/tokenization.cpp.i
.PHONY : src/cli/parser/tokenization.cpp.i

src/cli/parser/tokenization.s: src/cli/parser/tokenization.cpp.s
.PHONY : src/cli/parser/tokenization.s

# target to generate assembly for a file
src/cli/parser/tokenization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/tokenization.cpp.s
.PHONY : src/cli/parser/tokenization.cpp.s

src/cli/parser/validator.o: src/cli/parser/validator.cpp.o
.PHONY : src/cli/parser/validator.o

# target to build an object file
src/cli/parser/validator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/validator.cpp.o
.PHONY : src/cli/parser/validator.cpp.o

src/cli/parser/validator.i: src/cli/parser/validator.cpp.i
.PHONY : src/cli/parser/validator.i

# target to preprocess a source file
src/cli/parser/validator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/validator.cpp.i
.PHONY : src/cli/parser/validator.cpp.i

src/cli/parser/validator.s: src/cli/parser/validator.cpp.s
.PHONY : src/cli/parser/validator.s

# target to generate assembly for a file
src/cli/parser/validator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/cli/parser/validator.cpp.s
.PHONY : src/cli/parser/validator.cpp.s

src/kls-main.o: src/kls-main.cpp.o
.PHONY : src/kls-main.o

# target to build an object file
src/kls-main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls.dir/build.make CMakeFiles/kls.dir/src/kls-main.cpp.o
.PHONY : src/kls-main.cpp.o

src/kls-main.i: src/kls-main.cpp.i
.PHONY : src/kls-main.i

# target to preprocess a source file
src/kls-main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls.dir/build.make CMakeFiles/kls.dir/src/kls-main.cpp.i
.PHONY : src/kls-main.cpp.i

src/kls-main.s: src/kls-main.cpp.s
.PHONY : src/kls-main.s

# target to generate assembly for a file
src/kls-main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls.dir/build.make CMakeFiles/kls.dir/src/kls-main.cpp.s
.PHONY : src/kls-main.cpp.s

src/platform/identity_resolver.o: src/platform/identity_resolver.cpp.o
.PHONY : src/platform/identity_resolver.o

# target to build an object file
src/platform/identity_resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/platform/identity_resolver.cpp.o
.PHONY : src/platform/identity_resolver.cpp.o

src/platform/identity_resolver.i: src/platform/identity_resolver.cpp.i
.PHONY : src/platform/identity_resolver.i

# target to preprocess a source file
src/platform/identity_resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/platform/identity_resolver.cpp.i
.PHONY : src/platform/identity_resolver.cpp.i

src/platform/identity_resolver.s: src/platform/identity_resolver.cpp.s
.PHONY : src/platform/identity_resolver.s

# target to generate assembly for a file
src/platform/identity_resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/platform/identity_resolver.cpp.s
.PHONY : src/platform/identity_resolver.cpp.s

src/platform/unique_fd.o: src/platform/unique_fd.cpp.o
.PHONY : src/platform/unique_fd.o

# target to build an object file
src/platform/unique_fd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/platform/unique_fd.cpp.o
.PHONY : src/platform/unique_fd.cpp.o

src/platform/unique_fd.i: src/platform/unique_fd.cpp.i
.PHONY : src/platform/unique_fd.i

# target to preprocess a source file
src/platform/unique_fd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/platform/unique_fd.cpp.i
.PHONY : src/platform/unique_fd.cpp.i

src/platform/unique_fd.s: src/platform/unique_fd.cpp.s
.PHONY : src/platform/unique_fd.s

# target to generate assembly for a file
src/platform/unique_fd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/platform/unique_fd.cpp.s
.PHONY : src/platform/unique_fd.cpp.s

src/report/render_report.o: src/report/render_report.cpp.o
.PHONY : src/report/render_report.o

# target to build an object file
src/report/render_report.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/report/render_report.cpp.o
.PHONY : src/report/render_report.cpp.o

src/report/render_report.i: src/report/render_report.cpp.i
.PHONY : src/report/render_report.i

# target to preprocess a source file
src/report/render_report.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/report/render_report.cpp.i
.PHONY : src/report/render_report.cpp.i

src/report/render_report.s: src/report/render_report.cpp.s
.PHONY : src/report/render_report.s

# target to generate assembly for a file
src/report/render_report.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/report/render_report.cpp.s
.PHONY : src/report/render_report.cpp.s

src/scanner/collect_metadata.o: src/scanner/collect_metadata.cpp.o
.PHONY : src/scanner/collect_metadata.o

# target to build an object file
src/scanner/collect_metadata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_scanner.dir/build.make CMakeFiles/kls_scanner.dir/src/scanner/collect_metadata.cpp.o
.PHONY : src/scanner/collect_metadata.cpp.o

src/scanner/collect_metadata.i: src/scanner/collect_metadata.cpp.i
.PHONY : src/scanner/collect_metadata.i

# target to preprocess a source file
src/scanner/collect_metadata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_scanner.dir/build.make CMakeFiles/kls_scanner.dir/src/scanner/collect_metadata.cpp.i
.PHONY : src/scanner/collect_metadata.cpp.i

src/scanner/collect_metadata.s: src/scanner/collect_metadata.cpp.s
.PHONY : src/scanner/collect_metadata.s

# target to generate assembly for a file
src/scanner/collect_metadata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_scanner.dir/build.make CMakeFiles/kls_scanner.dir/src/scanner/collect_metadata.cpp.s
.PHONY : src/scanner/collect_metadata.cpp.s

src/scanner/scanner.o: src/scanner/scanner.cpp.o
.PHONY : src/scanner/scanner.o

# target to build an object file
src/scanner/scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_scanner.dir/build.make CMakeFiles/kls_scanner.dir/src/scanner/scanner.cpp.o
.PHONY : src/scanner/scanner.cpp.o

src/scanner/scanner.i: src/scanner/scanner.cpp.i
.PHONY : src/scanner/scanner.i

# target to preprocess a source file
src/scanner/scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_scanner.dir/build.make CMakeFiles/kls_scanner.dir/src/scanner/scanner.cpp.i
.PHONY : src/scanner/scanner.cpp.i

src/scanner/scanner.s: src/scanner/scanner.cpp.s
.PHONY : src/scanner/scanner.s

# target to generate assembly for a file
src/scanner/scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_scanner.dir/build.make CMakeFiles/kls_scanner.dir/src/scanner/scanner.cpp.s
.PHONY : src/scanner/scanner.cpp.s

src/white-list-routes/white-list-routes.o: src/white-list-routes/white-list-routes.cpp.o
.PHONY : src/white-list-routes/white-list-routes.o

# target to build an object file
src/white-list-routes/white-list-routes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/white-list-routes/white-list-routes.cpp.o
.PHONY : src/white-list-routes/white-list-routes.cpp.o

src/white-list-routes/white-list-routes.i: src/white-list-routes/white-list-routes.cpp.i
.PHONY : src/white-list-routes/white-list-routes.i

# target to preprocess a source file
src/white-list-routes/white-list-routes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/white-list-routes/white-list-routes.cpp.i
.PHONY : src/white-list-routes/white-list-routes.cpp.i

src/white-list-routes/white-list-routes.s: src/white-list-routes/white-list-routes.cpp.s
.PHONY : src/white-list-routes/white-list-routes.s

# target to generate assembly for a file
src/white-list-routes/white-list-routes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kls_core.dir/build.make CMakeFiles/kls_core.dir/src/white-list-routes/white-list-routes.cpp.s
.PHONY : src/white-list-routes/white-list-routes.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... compress_man"
	@echo "... uninstall"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... kls"
	@echo "... kls_core"
	@echo "... kls_scanner"
	@echo "... kls_tests"
	@echo "... src/CAPABILITIES-register/capabilities-register-log.o"
	@echo "... src/CAPABILITIES-register/capabilities-register-log.i"
	@echo "... src/CAPABILITIES-register/capabilities-register-log.s"
	@echo "... src/CAPABILITIES-register/capabilities-register.o"
	@echo "... src/CAPABILITIES-register/capabilities-register.i"
	@echo "... src/CAPABILITIES-register/capabilities-register.s"
	@echo "... src/CAPABILITIES-register/print-capabilities.o"
	@echo "... src/CAPABILITIES-register/print-capabilities.i"
	@echo "... src/CAPABILITIES-register/print-capabilities.s"
	@echo "... src/SUID-SGID-register/health-register.o"
	@echo "... src/SUID-SGID-register/health-register.i"
	@echo "... src/SUID-SGID-register/health-register.s"
	@echo "... src/SUID-SGID-register/print-health-flags.o"
	@echo "... src/SUID-SGID-register/print-health-flags.i"
	@echo "... src/SUID-SGID-register/print-health-flags.s"
	@echo "... src/SUID-SGID-register/suid-sgid-register-table.o"
	@echo "... src/SUID-SGID-register/suid-sgid-register-table.i"
	@echo "... src/SUID-SGID-register/suid-sgid-register-table.s"
	@echo "... src/analyzers/capability_analyzer.o"
	@echo "... src/analyzers/capability_analyzer.i"
	@echo "... src/analyzers/capability_analyzer.s"
	@echo "... src/analyzers/health_analyzer.o"
	@echo "... src/analyzers/health_analyzer.i"
	@echo "... src/analyzers/health_analyzer.s"
	@echo "... src/cli/command/list.o"
	@echo "... src/cli/command/list.i"
	@echo "... src/cli/command/list.s"
	@echo "... src/cli/error/error_handler.o"
	@echo "... src/cli/error/error_handler.i"
	@echo "... src/cli/error/error_handler.s"
	@echo "... src/cli/option/option-get-option.o"
	@echo "... src/cli/option/option-get-option.i"
	@echo "... src/cli/option/option-get-option.s"
	@echo "... src/cli/option/option-information.o"
	@echo "... src/cli/option/option-information.i"
	@echo "... src/cli/option/option-information.s"
	@echo "... src/cli/option/special-option/help-handler.o"
	@echo "... src/cli/option/special-option/help-handler.i"
	@echo "... src/cli/option/special-option/help-handler.s"
	@echo "... src/cli/option/special-option/version-handler.o"
	@echo "... src/cli/option/special-option/version-handler.i"
	@echo "... src/cli/option/special-option/version-handler.s"
	@echo "... src/cli/parser/executor.o"
	@echo "... src/cli/parser/executor.i"
	@echo "... src/cli/parser/executor.s"
	@echo "... src/cli/parser/parsing.o"
	@echo "... src/cli/parser/parsing.i"
	@echo "... src/cli/parser/parsing.s"
	@echo "... src/cli/parser/tokenization.o"
	@echo "... src/cli/parser/tokenization.i"
	@echo "... src/cli/parser/tokenization.s"
	@echo "... src/cli/parser/validator.o"
	@echo "... src/cli/parser/validator.i"
	@echo "... src/cli/parser/validator.s"
	@echo "... src/kls-main.o"
	@echo "... src/kls-main.i"
	@echo "... src/kls-main.s"
	@echo "... src/platform/identity_resolver.o"
	@echo "... src/platform/identity_resolver.i"
	@echo "... src/platform/identity_resolver.s"
	@echo "... src/platform/unique_fd.o"
	@echo "... src/platform/unique_fd.i"
	@echo "... src/platform/unique_fd.s"
	@echo "... src/report/render_report.o"
	@echo "... src/report/render_report.i"
	@echo "... src/report/render_report.s"
	@echo "... src/scanner/collect_metadata.o"
	@echo "... src/scanner/collect_metadata.i"
	@echo "... src/scanner/collect_metadata.s"
	@echo "... src/scanner/scanner.o"
	@echo "... src/scanner/scanner.i"
	@echo "... src/scanner/scanner.s"
	@echo "... src/white-list-routes/white-list-routes.o"
	@echo "... src/white-list-routes/white-list-routes.i"
	@echo "... src/white-list-routes/white-list-routes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

